package com.zhou.mapper;

import com.zhou.pojo.OrdOrderinfo;
import com.zhou.pojo.OrdOrderinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdOrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int countByExample(OrdOrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int deleteByExample(OrdOrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int insert(OrdOrderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int insertSelective(OrdOrderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    List<OrdOrderinfo> selectByExample(OrdOrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    OrdOrderinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrdOrderinfo record, @Param("example") OrdOrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int updateByExample(@Param("record") OrdOrderinfo record, @Param("example") OrdOrderinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int updateByPrimaryKeySelective(OrdOrderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    int updateByPrimaryKey(OrdOrderinfo record);
}