package com.zhou.mapper;

import com.zhou.pojo.ProProduct;
import com.zhou.pojo.ProProductExample;
import com.zhou.pojo.ProProductWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int countByExample(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int deleteByExample(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int insert(ProProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int insertSelective(ProProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    List<ProProductWithBLOBs> selectByExampleWithBLOBs(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    List<ProProduct> selectByExample(ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    ProProductWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProProductWithBLOBs record, @Param("example") ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProProductWithBLOBs record, @Param("example") ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int updateByExample(@Param("record") ProProduct record, @Param("example") ProProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int updateByPrimaryKeySelective(ProProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProProductWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    int updateByPrimaryKey(ProProduct record);
}