package com.zhou.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrdOrderinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public OrdOrderinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRouteidIsNull() {
            addCriterion("RouteID is null");
            return (Criteria) this;
        }

        public Criteria andRouteidIsNotNull() {
            addCriterion("RouteID is not null");
            return (Criteria) this;
        }

        public Criteria andRouteidEqualTo(String value) {
            addCriterion("RouteID =", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidNotEqualTo(String value) {
            addCriterion("RouteID <>", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidGreaterThan(String value) {
            addCriterion("RouteID >", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidGreaterThanOrEqualTo(String value) {
            addCriterion("RouteID >=", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidLessThan(String value) {
            addCriterion("RouteID <", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidLessThanOrEqualTo(String value) {
            addCriterion("RouteID <=", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidLike(String value) {
            addCriterion("RouteID like", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidNotLike(String value) {
            addCriterion("RouteID not like", value, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidIn(List<String> values) {
            addCriterion("RouteID in", values, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidNotIn(List<String> values) {
            addCriterion("RouteID not in", values, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidBetween(String value1, String value2) {
            addCriterion("RouteID between", value1, value2, "routeid");
            return (Criteria) this;
        }

        public Criteria andRouteidNotBetween(String value1, String value2) {
            addCriterion("RouteID not between", value1, value2, "routeid");
            return (Criteria) this;
        }

        public Criteria andTouridIsNull() {
            addCriterion("TourID is null");
            return (Criteria) this;
        }

        public Criteria andTouridIsNotNull() {
            addCriterion("TourID is not null");
            return (Criteria) this;
        }

        public Criteria andTouridEqualTo(String value) {
            addCriterion("TourID =", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridNotEqualTo(String value) {
            addCriterion("TourID <>", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridGreaterThan(String value) {
            addCriterion("TourID >", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridGreaterThanOrEqualTo(String value) {
            addCriterion("TourID >=", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridLessThan(String value) {
            addCriterion("TourID <", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridLessThanOrEqualTo(String value) {
            addCriterion("TourID <=", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridLike(String value) {
            addCriterion("TourID like", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridNotLike(String value) {
            addCriterion("TourID not like", value, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridIn(List<String> values) {
            addCriterion("TourID in", values, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridNotIn(List<String> values) {
            addCriterion("TourID not in", values, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridBetween(String value1, String value2) {
            addCriterion("TourID between", value1, value2, "tourid");
            return (Criteria) this;
        }

        public Criteria andTouridNotBetween(String value1, String value2) {
            addCriterion("TourID not between", value1, value2, "tourid");
            return (Criteria) this;
        }

        public Criteria andOrdernameIsNull() {
            addCriterion("OrderName is null");
            return (Criteria) this;
        }

        public Criteria andOrdernameIsNotNull() {
            addCriterion("OrderName is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernameEqualTo(String value) {
            addCriterion("OrderName =", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameNotEqualTo(String value) {
            addCriterion("OrderName <>", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameGreaterThan(String value) {
            addCriterion("OrderName >", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameGreaterThanOrEqualTo(String value) {
            addCriterion("OrderName >=", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameLessThan(String value) {
            addCriterion("OrderName <", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameLessThanOrEqualTo(String value) {
            addCriterion("OrderName <=", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameLike(String value) {
            addCriterion("OrderName like", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameNotLike(String value) {
            addCriterion("OrderName not like", value, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameIn(List<String> values) {
            addCriterion("OrderName in", values, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameNotIn(List<String> values) {
            addCriterion("OrderName not in", values, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameBetween(String value1, String value2) {
            addCriterion("OrderName between", value1, value2, "ordername");
            return (Criteria) this;
        }

        public Criteria andOrdernameNotBetween(String value1, String value2) {
            addCriterion("OrderName not between", value1, value2, "ordername");
            return (Criteria) this;
        }

        public Criteria andScheduledaysIsNull() {
            addCriterion("ScheduleDays is null");
            return (Criteria) this;
        }

        public Criteria andScheduledaysIsNotNull() {
            addCriterion("ScheduleDays is not null");
            return (Criteria) this;
        }

        public Criteria andScheduledaysEqualTo(Integer value) {
            addCriterion("ScheduleDays =", value, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysNotEqualTo(Integer value) {
            addCriterion("ScheduleDays <>", value, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysGreaterThan(Integer value) {
            addCriterion("ScheduleDays >", value, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("ScheduleDays >=", value, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysLessThan(Integer value) {
            addCriterion("ScheduleDays <", value, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysLessThanOrEqualTo(Integer value) {
            addCriterion("ScheduleDays <=", value, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysIn(List<Integer> values) {
            addCriterion("ScheduleDays in", values, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysNotIn(List<Integer> values) {
            addCriterion("ScheduleDays not in", values, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysBetween(Integer value1, Integer value2) {
            addCriterion("ScheduleDays between", value1, value2, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andScheduledaysNotBetween(Integer value1, Integer value2) {
            addCriterion("ScheduleDays not between", value1, value2, "scheduledays");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("Category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("Category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(Integer value) {
            addCriterion("Category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(Integer value) {
            addCriterion("Category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(Integer value) {
            addCriterion("Category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("Category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(Integer value) {
            addCriterion("Category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(Integer value) {
            addCriterion("Category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<Integer> values) {
            addCriterion("Category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<Integer> values) {
            addCriterion("Category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(Integer value1, Integer value2) {
            addCriterion("Category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(Integer value1, Integer value2) {
            addCriterion("Category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIsNull() {
            addCriterion("OrderType is null");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIsNotNull() {
            addCriterion("OrderType is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertypeEqualTo(Integer value) {
            addCriterion("OrderType =", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotEqualTo(Integer value) {
            addCriterion("OrderType <>", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeGreaterThan(Integer value) {
            addCriterion("OrderType >", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("OrderType >=", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeLessThan(Integer value) {
            addCriterion("OrderType <", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeLessThanOrEqualTo(Integer value) {
            addCriterion("OrderType <=", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIn(List<Integer> values) {
            addCriterion("OrderType in", values, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotIn(List<Integer> values) {
            addCriterion("OrderType not in", values, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeBetween(Integer value1, Integer value2) {
            addCriterion("OrderType between", value1, value2, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotBetween(Integer value1, Integer value2) {
            addCriterion("OrderType not between", value1, value2, "ordertype");
            return (Criteria) this;
        }

        public Criteria andTourdateIsNull() {
            addCriterion("TourDate is null");
            return (Criteria) this;
        }

        public Criteria andTourdateIsNotNull() {
            addCriterion("TourDate is not null");
            return (Criteria) this;
        }

        public Criteria andTourdateEqualTo(Date value) {
            addCriterion("TourDate =", value, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateNotEqualTo(Date value) {
            addCriterion("TourDate <>", value, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateGreaterThan(Date value) {
            addCriterion("TourDate >", value, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateGreaterThanOrEqualTo(Date value) {
            addCriterion("TourDate >=", value, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateLessThan(Date value) {
            addCriterion("TourDate <", value, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateLessThanOrEqualTo(Date value) {
            addCriterion("TourDate <=", value, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateIn(List<Date> values) {
            addCriterion("TourDate in", values, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateNotIn(List<Date> values) {
            addCriterion("TourDate not in", values, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateBetween(Date value1, Date value2) {
            addCriterion("TourDate between", value1, value2, "tourdate");
            return (Criteria) this;
        }

        public Criteria andTourdateNotBetween(Date value1, Date value2) {
            addCriterion("TourDate not between", value1, value2, "tourdate");
            return (Criteria) this;
        }

        public Criteria andReturndateIsNull() {
            addCriterion("ReturnDate is null");
            return (Criteria) this;
        }

        public Criteria andReturndateIsNotNull() {
            addCriterion("ReturnDate is not null");
            return (Criteria) this;
        }

        public Criteria andReturndateEqualTo(Date value) {
            addCriterion("ReturnDate =", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotEqualTo(Date value) {
            addCriterion("ReturnDate <>", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateGreaterThan(Date value) {
            addCriterion("ReturnDate >", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateGreaterThanOrEqualTo(Date value) {
            addCriterion("ReturnDate >=", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateLessThan(Date value) {
            addCriterion("ReturnDate <", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateLessThanOrEqualTo(Date value) {
            addCriterion("ReturnDate <=", value, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateIn(List<Date> values) {
            addCriterion("ReturnDate in", values, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotIn(List<Date> values) {
            addCriterion("ReturnDate not in", values, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateBetween(Date value1, Date value2) {
            addCriterion("ReturnDate between", value1, value2, "returndate");
            return (Criteria) this;
        }

        public Criteria andReturndateNotBetween(Date value1, Date value2) {
            addCriterion("ReturnDate not between", value1, value2, "returndate");
            return (Criteria) this;
        }

        public Criteria andDepnameIsNull() {
            addCriterion("DepName is null");
            return (Criteria) this;
        }

        public Criteria andDepnameIsNotNull() {
            addCriterion("DepName is not null");
            return (Criteria) this;
        }

        public Criteria andDepnameEqualTo(String value) {
            addCriterion("DepName =", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotEqualTo(String value) {
            addCriterion("DepName <>", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameGreaterThan(String value) {
            addCriterion("DepName >", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameGreaterThanOrEqualTo(String value) {
            addCriterion("DepName >=", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameLessThan(String value) {
            addCriterion("DepName <", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameLessThanOrEqualTo(String value) {
            addCriterion("DepName <=", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameLike(String value) {
            addCriterion("DepName like", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotLike(String value) {
            addCriterion("DepName not like", value, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameIn(List<String> values) {
            addCriterion("DepName in", values, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotIn(List<String> values) {
            addCriterion("DepName not in", values, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameBetween(String value1, String value2) {
            addCriterion("DepName between", value1, value2, "depname");
            return (Criteria) this;
        }

        public Criteria andDepnameNotBetween(String value1, String value2) {
            addCriterion("DepName not between", value1, value2, "depname");
            return (Criteria) this;
        }

        public Criteria andDestnameIsNull() {
            addCriterion("DestName is null");
            return (Criteria) this;
        }

        public Criteria andDestnameIsNotNull() {
            addCriterion("DestName is not null");
            return (Criteria) this;
        }

        public Criteria andDestnameEqualTo(String value) {
            addCriterion("DestName =", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameNotEqualTo(String value) {
            addCriterion("DestName <>", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameGreaterThan(String value) {
            addCriterion("DestName >", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameGreaterThanOrEqualTo(String value) {
            addCriterion("DestName >=", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameLessThan(String value) {
            addCriterion("DestName <", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameLessThanOrEqualTo(String value) {
            addCriterion("DestName <=", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameLike(String value) {
            addCriterion("DestName like", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameNotLike(String value) {
            addCriterion("DestName not like", value, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameIn(List<String> values) {
            addCriterion("DestName in", values, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameNotIn(List<String> values) {
            addCriterion("DestName not in", values, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameBetween(String value1, String value2) {
            addCriterion("DestName between", value1, value2, "destname");
            return (Criteria) this;
        }

        public Criteria andDestnameNotBetween(String value1, String value2) {
            addCriterion("DestName not between", value1, value2, "destname");
            return (Criteria) this;
        }

        public Criteria andDestidIsNull() {
            addCriterion("DestID is null");
            return (Criteria) this;
        }

        public Criteria andDestidIsNotNull() {
            addCriterion("DestID is not null");
            return (Criteria) this;
        }

        public Criteria andDestidEqualTo(String value) {
            addCriterion("DestID =", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidNotEqualTo(String value) {
            addCriterion("DestID <>", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidGreaterThan(String value) {
            addCriterion("DestID >", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidGreaterThanOrEqualTo(String value) {
            addCriterion("DestID >=", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidLessThan(String value) {
            addCriterion("DestID <", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidLessThanOrEqualTo(String value) {
            addCriterion("DestID <=", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidLike(String value) {
            addCriterion("DestID like", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidNotLike(String value) {
            addCriterion("DestID not like", value, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidIn(List<String> values) {
            addCriterion("DestID in", values, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidNotIn(List<String> values) {
            addCriterion("DestID not in", values, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidBetween(String value1, String value2) {
            addCriterion("DestID between", value1, value2, "destid");
            return (Criteria) this;
        }

        public Criteria andDestidNotBetween(String value1, String value2) {
            addCriterion("DestID not between", value1, value2, "destid");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("OrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("OrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernoEqualTo(String value) {
            addCriterion("OrderNo =", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotEqualTo(String value) {
            addCriterion("OrderNo <>", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThan(String value) {
            addCriterion("OrderNo >", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("OrderNo >=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThan(String value) {
            addCriterion("OrderNo <", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(String value) {
            addCriterion("OrderNo <=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLike(String value) {
            addCriterion("OrderNo like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotLike(String value) {
            addCriterion("OrderNo not like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIn(List<String> values) {
            addCriterion("OrderNo in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotIn(List<String> values) {
            addCriterion("OrderNo not in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoBetween(String value1, String value2) {
            addCriterion("OrderNo between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotBetween(String value1, String value2) {
            addCriterion("OrderNo not between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidIsNull() {
            addCriterion("CustomerUnitID is null");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidIsNotNull() {
            addCriterion("CustomerUnitID is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidEqualTo(String value) {
            addCriterion("CustomerUnitID =", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidNotEqualTo(String value) {
            addCriterion("CustomerUnitID <>", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidGreaterThan(String value) {
            addCriterion("CustomerUnitID >", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerUnitID >=", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidLessThan(String value) {
            addCriterion("CustomerUnitID <", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidLessThanOrEqualTo(String value) {
            addCriterion("CustomerUnitID <=", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidLike(String value) {
            addCriterion("CustomerUnitID like", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidNotLike(String value) {
            addCriterion("CustomerUnitID not like", value, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidIn(List<String> values) {
            addCriterion("CustomerUnitID in", values, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidNotIn(List<String> values) {
            addCriterion("CustomerUnitID not in", values, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidBetween(String value1, String value2) {
            addCriterion("CustomerUnitID between", value1, value2, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomerunitidNotBetween(String value1, String value2) {
            addCriterion("CustomerUnitID not between", value1, value2, "customerunitid");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNull() {
            addCriterion("CustomerName is null");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNotNull() {
            addCriterion("CustomerName is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernameEqualTo(String value) {
            addCriterion("CustomerName =", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotEqualTo(String value) {
            addCriterion("CustomerName <>", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThan(String value) {
            addCriterion("CustomerName >", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerName >=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThan(String value) {
            addCriterion("CustomerName <", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThanOrEqualTo(String value) {
            addCriterion("CustomerName <=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLike(String value) {
            addCriterion("CustomerName like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotLike(String value) {
            addCriterion("CustomerName not like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameIn(List<String> values) {
            addCriterion("CustomerName in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotIn(List<String> values) {
            addCriterion("CustomerName not in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameBetween(String value1, String value2) {
            addCriterion("CustomerName between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotBetween(String value1, String value2) {
            addCriterion("CustomerName not between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidIsNull() {
            addCriterion("OrderSourceID is null");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidIsNotNull() {
            addCriterion("OrderSourceID is not null");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidEqualTo(String value) {
            addCriterion("OrderSourceID =", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidNotEqualTo(String value) {
            addCriterion("OrderSourceID <>", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidGreaterThan(String value) {
            addCriterion("OrderSourceID >", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidGreaterThanOrEqualTo(String value) {
            addCriterion("OrderSourceID >=", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidLessThan(String value) {
            addCriterion("OrderSourceID <", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidLessThanOrEqualTo(String value) {
            addCriterion("OrderSourceID <=", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidLike(String value) {
            addCriterion("OrderSourceID like", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidNotLike(String value) {
            addCriterion("OrderSourceID not like", value, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidIn(List<String> values) {
            addCriterion("OrderSourceID in", values, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidNotIn(List<String> values) {
            addCriterion("OrderSourceID not in", values, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidBetween(String value1, String value2) {
            addCriterion("OrderSourceID between", value1, value2, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceidNotBetween(String value1, String value2) {
            addCriterion("OrderSourceID not between", value1, value2, "ordersourceid");
            return (Criteria) this;
        }

        public Criteria andOrdersourceIsNull() {
            addCriterion("OrderSource is null");
            return (Criteria) this;
        }

        public Criteria andOrdersourceIsNotNull() {
            addCriterion("OrderSource is not null");
            return (Criteria) this;
        }

        public Criteria andOrdersourceEqualTo(String value) {
            addCriterion("OrderSource =", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceNotEqualTo(String value) {
            addCriterion("OrderSource <>", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceGreaterThan(String value) {
            addCriterion("OrderSource >", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceGreaterThanOrEqualTo(String value) {
            addCriterion("OrderSource >=", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceLessThan(String value) {
            addCriterion("OrderSource <", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceLessThanOrEqualTo(String value) {
            addCriterion("OrderSource <=", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceLike(String value) {
            addCriterion("OrderSource like", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceNotLike(String value) {
            addCriterion("OrderSource not like", value, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceIn(List<String> values) {
            addCriterion("OrderSource in", values, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceNotIn(List<String> values) {
            addCriterion("OrderSource not in", values, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceBetween(String value1, String value2) {
            addCriterion("OrderSource between", value1, value2, "ordersource");
            return (Criteria) this;
        }

        public Criteria andOrdersourceNotBetween(String value1, String value2) {
            addCriterion("OrderSource not between", value1, value2, "ordersource");
            return (Criteria) this;
        }

        public Criteria andContactIsNull() {
            addCriterion("Contact is null");
            return (Criteria) this;
        }

        public Criteria andContactIsNotNull() {
            addCriterion("Contact is not null");
            return (Criteria) this;
        }

        public Criteria andContactEqualTo(String value) {
            addCriterion("Contact =", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotEqualTo(String value) {
            addCriterion("Contact <>", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThan(String value) {
            addCriterion("Contact >", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThanOrEqualTo(String value) {
            addCriterion("Contact >=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThan(String value) {
            addCriterion("Contact <", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThanOrEqualTo(String value) {
            addCriterion("Contact <=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLike(String value) {
            addCriterion("Contact like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotLike(String value) {
            addCriterion("Contact not like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactIn(List<String> values) {
            addCriterion("Contact in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotIn(List<String> values) {
            addCriterion("Contact not in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactBetween(String value1, String value2) {
            addCriterion("Contact between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotBetween(String value1, String value2) {
            addCriterion("Contact not between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("Mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("Mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("Mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("Mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("Mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("Mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("Mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("Mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("Mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("Mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("Mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("Mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("Mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("Mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andHasairticketIsNull() {
            addCriterion("HasAirTicket is null");
            return (Criteria) this;
        }

        public Criteria andHasairticketIsNotNull() {
            addCriterion("HasAirTicket is not null");
            return (Criteria) this;
        }

        public Criteria andHasairticketEqualTo(Integer value) {
            addCriterion("HasAirTicket =", value, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketNotEqualTo(Integer value) {
            addCriterion("HasAirTicket <>", value, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketGreaterThan(Integer value) {
            addCriterion("HasAirTicket >", value, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketGreaterThanOrEqualTo(Integer value) {
            addCriterion("HasAirTicket >=", value, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketLessThan(Integer value) {
            addCriterion("HasAirTicket <", value, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketLessThanOrEqualTo(Integer value) {
            addCriterion("HasAirTicket <=", value, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketIn(List<Integer> values) {
            addCriterion("HasAirTicket in", values, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketNotIn(List<Integer> values) {
            addCriterion("HasAirTicket not in", values, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketBetween(Integer value1, Integer value2) {
            addCriterion("HasAirTicket between", value1, value2, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andHasairticketNotBetween(Integer value1, Integer value2) {
            addCriterion("HasAirTicket not between", value1, value2, "hasairticket");
            return (Criteria) this;
        }

        public Criteria andAdjustamtIsNull() {
            addCriterion("AdjustAmt is null");
            return (Criteria) this;
        }

        public Criteria andAdjustamtIsNotNull() {
            addCriterion("AdjustAmt is not null");
            return (Criteria) this;
        }

        public Criteria andAdjustamtEqualTo(BigDecimal value) {
            addCriterion("AdjustAmt =", value, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtNotEqualTo(BigDecimal value) {
            addCriterion("AdjustAmt <>", value, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtGreaterThan(BigDecimal value) {
            addCriterion("AdjustAmt >", value, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AdjustAmt >=", value, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtLessThan(BigDecimal value) {
            addCriterion("AdjustAmt <", value, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AdjustAmt <=", value, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtIn(List<BigDecimal> values) {
            addCriterion("AdjustAmt in", values, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtNotIn(List<BigDecimal> values) {
            addCriterion("AdjustAmt not in", values, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AdjustAmt between", value1, value2, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andAdjustamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AdjustAmt not between", value1, value2, "adjustamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtIsNull() {
            addCriterion("ReceivableAmt is null");
            return (Criteria) this;
        }

        public Criteria andReceivableamtIsNotNull() {
            addCriterion("ReceivableAmt is not null");
            return (Criteria) this;
        }

        public Criteria andReceivableamtEqualTo(BigDecimal value) {
            addCriterion("ReceivableAmt =", value, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtNotEqualTo(BigDecimal value) {
            addCriterion("ReceivableAmt <>", value, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtGreaterThan(BigDecimal value) {
            addCriterion("ReceivableAmt >", value, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ReceivableAmt >=", value, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtLessThan(BigDecimal value) {
            addCriterion("ReceivableAmt <", value, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ReceivableAmt <=", value, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtIn(List<BigDecimal> values) {
            addCriterion("ReceivableAmt in", values, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtNotIn(List<BigDecimal> values) {
            addCriterion("ReceivableAmt not in", values, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ReceivableAmt between", value1, value2, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andReceivableamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ReceivableAmt not between", value1, value2, "receivableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtIsNull() {
            addCriterion("PayableAmt is null");
            return (Criteria) this;
        }

        public Criteria andPayableamtIsNotNull() {
            addCriterion("PayableAmt is not null");
            return (Criteria) this;
        }

        public Criteria andPayableamtEqualTo(BigDecimal value) {
            addCriterion("PayableAmt =", value, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtNotEqualTo(BigDecimal value) {
            addCriterion("PayableAmt <>", value, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtGreaterThan(BigDecimal value) {
            addCriterion("PayableAmt >", value, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PayableAmt >=", value, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtLessThan(BigDecimal value) {
            addCriterion("PayableAmt <", value, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PayableAmt <=", value, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtIn(List<BigDecimal> values) {
            addCriterion("PayableAmt in", values, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtNotIn(List<BigDecimal> values) {
            addCriterion("PayableAmt not in", values, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PayableAmt between", value1, value2, "payableamt");
            return (Criteria) this;
        }

        public Criteria andPayableamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PayableAmt not between", value1, value2, "payableamt");
            return (Criteria) this;
        }

        public Criteria andAdultnumIsNull() {
            addCriterion("AdultNum is null");
            return (Criteria) this;
        }

        public Criteria andAdultnumIsNotNull() {
            addCriterion("AdultNum is not null");
            return (Criteria) this;
        }

        public Criteria andAdultnumEqualTo(Integer value) {
            addCriterion("AdultNum =", value, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumNotEqualTo(Integer value) {
            addCriterion("AdultNum <>", value, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumGreaterThan(Integer value) {
            addCriterion("AdultNum >", value, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("AdultNum >=", value, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumLessThan(Integer value) {
            addCriterion("AdultNum <", value, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumLessThanOrEqualTo(Integer value) {
            addCriterion("AdultNum <=", value, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumIn(List<Integer> values) {
            addCriterion("AdultNum in", values, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumNotIn(List<Integer> values) {
            addCriterion("AdultNum not in", values, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumBetween(Integer value1, Integer value2) {
            addCriterion("AdultNum between", value1, value2, "adultnum");
            return (Criteria) this;
        }

        public Criteria andAdultnumNotBetween(Integer value1, Integer value2) {
            addCriterion("AdultNum not between", value1, value2, "adultnum");
            return (Criteria) this;
        }

        public Criteria andChildnumIsNull() {
            addCriterion("ChildNum is null");
            return (Criteria) this;
        }

        public Criteria andChildnumIsNotNull() {
            addCriterion("ChildNum is not null");
            return (Criteria) this;
        }

        public Criteria andChildnumEqualTo(Integer value) {
            addCriterion("ChildNum =", value, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumNotEqualTo(Integer value) {
            addCriterion("ChildNum <>", value, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumGreaterThan(Integer value) {
            addCriterion("ChildNum >", value, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ChildNum >=", value, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumLessThan(Integer value) {
            addCriterion("ChildNum <", value, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumLessThanOrEqualTo(Integer value) {
            addCriterion("ChildNum <=", value, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumIn(List<Integer> values) {
            addCriterion("ChildNum in", values, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumNotIn(List<Integer> values) {
            addCriterion("ChildNum not in", values, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumBetween(Integer value1, Integer value2) {
            addCriterion("ChildNum between", value1, value2, "childnum");
            return (Criteria) this;
        }

        public Criteria andChildnumNotBetween(Integer value1, Integer value2) {
            addCriterion("ChildNum not between", value1, value2, "childnum");
            return (Criteria) this;
        }

        public Criteria andGuidenumIsNull() {
            addCriterion("GuideNum is null");
            return (Criteria) this;
        }

        public Criteria andGuidenumIsNotNull() {
            addCriterion("GuideNum is not null");
            return (Criteria) this;
        }

        public Criteria andGuidenumEqualTo(Integer value) {
            addCriterion("GuideNum =", value, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumNotEqualTo(Integer value) {
            addCriterion("GuideNum <>", value, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumGreaterThan(Integer value) {
            addCriterion("GuideNum >", value, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("GuideNum >=", value, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumLessThan(Integer value) {
            addCriterion("GuideNum <", value, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumLessThanOrEqualTo(Integer value) {
            addCriterion("GuideNum <=", value, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumIn(List<Integer> values) {
            addCriterion("GuideNum in", values, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumNotIn(List<Integer> values) {
            addCriterion("GuideNum not in", values, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumBetween(Integer value1, Integer value2) {
            addCriterion("GuideNum between", value1, value2, "guidenum");
            return (Criteria) this;
        }

        public Criteria andGuidenumNotBetween(Integer value1, Integer value2) {
            addCriterion("GuideNum not between", value1, value2, "guidenum");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("Comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("Comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("Comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("Comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("Comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("Comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("Comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("Comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("Comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("Comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("Comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("Comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("Comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("Comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNull() {
            addCriterion("CreatedDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNotNull() {
            addCriterion("CreatedDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateddateEqualTo(Date value) {
            addCriterion("CreatedDate =", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotEqualTo(Date value) {
            addCriterion("CreatedDate <>", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThan(Date value) {
            addCriterion("CreatedDate >", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedDate >=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThan(Date value) {
            addCriterion("CreatedDate <", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThanOrEqualTo(Date value) {
            addCriterion("CreatedDate <=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateIn(List<Date> values) {
            addCriterion("CreatedDate in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotIn(List<Date> values) {
            addCriterion("CreatedDate not in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateBetween(Date value1, Date value2) {
            addCriterion("CreatedDate between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotBetween(Date value1, Date value2) {
            addCriterion("CreatedDate not between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNull() {
            addCriterion("CreatedBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNotNull() {
            addCriterion("CreatedBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyEqualTo(String value) {
            addCriterion("CreatedBy =", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotEqualTo(String value) {
            addCriterion("CreatedBy <>", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThan(String value) {
            addCriterion("CreatedBy >", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedBy >=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThan(String value) {
            addCriterion("CreatedBy <", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThanOrEqualTo(String value) {
            addCriterion("CreatedBy <=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLike(String value) {
            addCriterion("CreatedBy like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotLike(String value) {
            addCriterion("CreatedBy not like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIn(List<String> values) {
            addCriterion("CreatedBy in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotIn(List<String> values) {
            addCriterion("CreatedBy not in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyBetween(String value1, String value2) {
            addCriterion("CreatedBy between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotBetween(String value1, String value2) {
            addCriterion("CreatedBy not between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidIsNull() {
            addCriterion("CreatedByID is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidIsNotNull() {
            addCriterion("CreatedByID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidEqualTo(String value) {
            addCriterion("CreatedByID =", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotEqualTo(String value) {
            addCriterion("CreatedByID <>", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidGreaterThan(String value) {
            addCriterion("CreatedByID >", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedByID >=", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidLessThan(String value) {
            addCriterion("CreatedByID <", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidLessThanOrEqualTo(String value) {
            addCriterion("CreatedByID <=", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidLike(String value) {
            addCriterion("CreatedByID like", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotLike(String value) {
            addCriterion("CreatedByID not like", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidIn(List<String> values) {
            addCriterion("CreatedByID in", values, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotIn(List<String> values) {
            addCriterion("CreatedByID not in", values, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidBetween(String value1, String value2) {
            addCriterion("CreatedByID between", value1, value2, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotBetween(String value1, String value2) {
            addCriterion("CreatedByID not between", value1, value2, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNull() {
            addCriterion("DeptID is null");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNotNull() {
            addCriterion("DeptID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptidEqualTo(String value) {
            addCriterion("DeptID =", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotEqualTo(String value) {
            addCriterion("DeptID <>", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThan(String value) {
            addCriterion("DeptID >", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("DeptID >=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThan(String value) {
            addCriterion("DeptID <", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThanOrEqualTo(String value) {
            addCriterion("DeptID <=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLike(String value) {
            addCriterion("DeptID like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotLike(String value) {
            addCriterion("DeptID not like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidIn(List<String> values) {
            addCriterion("DeptID in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotIn(List<String> values) {
            addCriterion("DeptID not in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidBetween(String value1, String value2) {
            addCriterion("DeptID between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotBetween(String value1, String value2) {
            addCriterion("DeptID not between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andReviseddateIsNull() {
            addCriterion("RevisedDate is null");
            return (Criteria) this;
        }

        public Criteria andReviseddateIsNotNull() {
            addCriterion("RevisedDate is not null");
            return (Criteria) this;
        }

        public Criteria andReviseddateEqualTo(Date value) {
            addCriterion("RevisedDate =", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateNotEqualTo(Date value) {
            addCriterion("RevisedDate <>", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateGreaterThan(Date value) {
            addCriterion("RevisedDate >", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateGreaterThanOrEqualTo(Date value) {
            addCriterion("RevisedDate >=", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateLessThan(Date value) {
            addCriterion("RevisedDate <", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateLessThanOrEqualTo(Date value) {
            addCriterion("RevisedDate <=", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateIn(List<Date> values) {
            addCriterion("RevisedDate in", values, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateNotIn(List<Date> values) {
            addCriterion("RevisedDate not in", values, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateBetween(Date value1, Date value2) {
            addCriterion("RevisedDate between", value1, value2, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateNotBetween(Date value1, Date value2) {
            addCriterion("RevisedDate not between", value1, value2, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andRevisedbyIsNull() {
            addCriterion("RevisedBy is null");
            return (Criteria) this;
        }

        public Criteria andRevisedbyIsNotNull() {
            addCriterion("RevisedBy is not null");
            return (Criteria) this;
        }

        public Criteria andRevisedbyEqualTo(String value) {
            addCriterion("RevisedBy =", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotEqualTo(String value) {
            addCriterion("RevisedBy <>", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyGreaterThan(String value) {
            addCriterion("RevisedBy >", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyGreaterThanOrEqualTo(String value) {
            addCriterion("RevisedBy >=", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyLessThan(String value) {
            addCriterion("RevisedBy <", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyLessThanOrEqualTo(String value) {
            addCriterion("RevisedBy <=", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyLike(String value) {
            addCriterion("RevisedBy like", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotLike(String value) {
            addCriterion("RevisedBy not like", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyIn(List<String> values) {
            addCriterion("RevisedBy in", values, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotIn(List<String> values) {
            addCriterion("RevisedBy not in", values, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyBetween(String value1, String value2) {
            addCriterion("RevisedBy between", value1, value2, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotBetween(String value1, String value2) {
            addCriterion("RevisedBy not between", value1, value2, "revisedby");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNull() {
            addCriterion("OrgID is null");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNotNull() {
            addCriterion("OrgID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidEqualTo(String value) {
            addCriterion("OrgID =", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotEqualTo(String value) {
            addCriterion("OrgID <>", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThan(String value) {
            addCriterion("OrgID >", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThanOrEqualTo(String value) {
            addCriterion("OrgID >=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThan(String value) {
            addCriterion("OrgID <", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThanOrEqualTo(String value) {
            addCriterion("OrgID <=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLike(String value) {
            addCriterion("OrgID like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotLike(String value) {
            addCriterion("OrgID not like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidIn(List<String> values) {
            addCriterion("OrgID in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotIn(List<String> values) {
            addCriterion("OrgID not in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidBetween(String value1, String value2) {
            addCriterion("OrgID between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotBetween(String value1, String value2) {
            addCriterion("OrgID not between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNull() {
            addCriterion("OrgName is null");
            return (Criteria) this;
        }

        public Criteria andOrgnameIsNotNull() {
            addCriterion("OrgName is not null");
            return (Criteria) this;
        }

        public Criteria andOrgnameEqualTo(String value) {
            addCriterion("OrgName =", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotEqualTo(String value) {
            addCriterion("OrgName <>", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThan(String value) {
            addCriterion("OrgName >", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameGreaterThanOrEqualTo(String value) {
            addCriterion("OrgName >=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThan(String value) {
            addCriterion("OrgName <", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLessThanOrEqualTo(String value) {
            addCriterion("OrgName <=", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameLike(String value) {
            addCriterion("OrgName like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotLike(String value) {
            addCriterion("OrgName not like", value, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameIn(List<String> values) {
            addCriterion("OrgName in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotIn(List<String> values) {
            addCriterion("OrgName not in", values, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameBetween(String value1, String value2) {
            addCriterion("OrgName between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andOrgnameNotBetween(String value1, String value2) {
            addCriterion("OrgName not between", value1, value2, "orgname");
            return (Criteria) this;
        }

        public Criteria andDatastatusIsNull() {
            addCriterion("DataStatus is null");
            return (Criteria) this;
        }

        public Criteria andDatastatusIsNotNull() {
            addCriterion("DataStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDatastatusEqualTo(Integer value) {
            addCriterion("DataStatus =", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusNotEqualTo(Integer value) {
            addCriterion("DataStatus <>", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusGreaterThan(Integer value) {
            addCriterion("DataStatus >", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("DataStatus >=", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusLessThan(Integer value) {
            addCriterion("DataStatus <", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusLessThanOrEqualTo(Integer value) {
            addCriterion("DataStatus <=", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusIn(List<Integer> values) {
            addCriterion("DataStatus in", values, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusNotIn(List<Integer> values) {
            addCriterion("DataStatus not in", values, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusBetween(Integer value1, Integer value2) {
            addCriterion("DataStatus between", value1, value2, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusNotBetween(Integer value1, Integer value2) {
            addCriterion("DataStatus not between", value1, value2, "datastatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusIsNull() {
            addCriterion("SignStatus is null");
            return (Criteria) this;
        }

        public Criteria andSignstatusIsNotNull() {
            addCriterion("SignStatus is not null");
            return (Criteria) this;
        }

        public Criteria andSignstatusEqualTo(Integer value) {
            addCriterion("SignStatus =", value, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusNotEqualTo(Integer value) {
            addCriterion("SignStatus <>", value, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusGreaterThan(Integer value) {
            addCriterion("SignStatus >", value, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("SignStatus >=", value, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusLessThan(Integer value) {
            addCriterion("SignStatus <", value, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusLessThanOrEqualTo(Integer value) {
            addCriterion("SignStatus <=", value, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusIn(List<Integer> values) {
            addCriterion("SignStatus in", values, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusNotIn(List<Integer> values) {
            addCriterion("SignStatus not in", values, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusBetween(Integer value1, Integer value2) {
            addCriterion("SignStatus between", value1, value2, "signstatus");
            return (Criteria) this;
        }

        public Criteria andSignstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("SignStatus not between", value1, value2, "signstatus");
            return (Criteria) this;
        }

        public Criteria andTourguideIsNull() {
            addCriterion("TourGuide is null");
            return (Criteria) this;
        }

        public Criteria andTourguideIsNotNull() {
            addCriterion("TourGuide is not null");
            return (Criteria) this;
        }

        public Criteria andTourguideEqualTo(String value) {
            addCriterion("TourGuide =", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideNotEqualTo(String value) {
            addCriterion("TourGuide <>", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideGreaterThan(String value) {
            addCriterion("TourGuide >", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideGreaterThanOrEqualTo(String value) {
            addCriterion("TourGuide >=", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideLessThan(String value) {
            addCriterion("TourGuide <", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideLessThanOrEqualTo(String value) {
            addCriterion("TourGuide <=", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideLike(String value) {
            addCriterion("TourGuide like", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideNotLike(String value) {
            addCriterion("TourGuide not like", value, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideIn(List<String> values) {
            addCriterion("TourGuide in", values, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideNotIn(List<String> values) {
            addCriterion("TourGuide not in", values, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideBetween(String value1, String value2) {
            addCriterion("TourGuide between", value1, value2, "tourguide");
            return (Criteria) this;
        }

        public Criteria andTourguideNotBetween(String value1, String value2) {
            addCriterion("TourGuide not between", value1, value2, "tourguide");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated do_not_delete_during_merge Mon May 14 15:16:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Ord_OrderInfo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}