package com.zhou.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class OrdOrderinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.ID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.RouteID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String routeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.TourID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String tourid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.OrderName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String ordername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.ScheduleDays
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer scheduledays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.Category
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.OrderType
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.TourDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Date tourdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.ReturnDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Date returndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.DepName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String depname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.DestName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String destname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.DestID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String destid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.OrderNo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.CustomerUnitID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String customerunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.CustomerName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.OrderSourceID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String ordersourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.OrderSource
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String ordersource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.Contact
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.Mobile
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.HasAirTicket
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer hasairticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.AdjustAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private BigDecimal adjustamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.ReceivableAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private BigDecimal receivableamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.PayableAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private BigDecimal payableamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.AdultNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer adultnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.ChildNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer childnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.GuideNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer guidenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.Comment
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.CreatedDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.CreatedBy
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.CreatedByID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String createdbyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.DeptID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.RevisedDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Date reviseddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.RevisedBy
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String revisedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.OrgID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.OrgName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String orgname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.DataStatus
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer datastatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.SignStatus
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private Integer signstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ord_OrderInfo.TourGuide
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    private String tourguide;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.ID
     *
     * @return the value of Ord_OrderInfo.ID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.ID
     *
     * @param id the value for Ord_OrderInfo.ID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.RouteID
     *
     * @return the value of Ord_OrderInfo.RouteID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.RouteID
     *
     * @param routeid the value for Ord_OrderInfo.RouteID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.TourID
     *
     * @return the value of Ord_OrderInfo.TourID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getTourid() {
        return tourid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.TourID
     *
     * @param tourid the value for Ord_OrderInfo.TourID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setTourid(String tourid) {
        this.tourid = tourid == null ? null : tourid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.OrderName
     *
     * @return the value of Ord_OrderInfo.OrderName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getOrdername() {
        return ordername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.OrderName
     *
     * @param ordername the value for Ord_OrderInfo.OrderName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrdername(String ordername) {
        this.ordername = ordername == null ? null : ordername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.ScheduleDays
     *
     * @return the value of Ord_OrderInfo.ScheduleDays
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getScheduledays() {
        return scheduledays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.ScheduleDays
     *
     * @param scheduledays the value for Ord_OrderInfo.ScheduleDays
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setScheduledays(Integer scheduledays) {
        this.scheduledays = scheduledays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.Category
     *
     * @return the value of Ord_OrderInfo.Category
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.Category
     *
     * @param category the value for Ord_OrderInfo.Category
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.OrderType
     *
     * @return the value of Ord_OrderInfo.OrderType
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.OrderType
     *
     * @param ordertype the value for Ord_OrderInfo.OrderType
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.TourDate
     *
     * @return the value of Ord_OrderInfo.TourDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Date getTourdate() {
        return tourdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.TourDate
     *
     * @param tourdate the value for Ord_OrderInfo.TourDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setTourdate(Date tourdate) {
        this.tourdate = tourdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.ReturnDate
     *
     * @return the value of Ord_OrderInfo.ReturnDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.ReturnDate
     *
     * @param returndate the value for Ord_OrderInfo.ReturnDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.DepName
     *
     * @return the value of Ord_OrderInfo.DepName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.DepName
     *
     * @param depname the value for Ord_OrderInfo.DepName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setDepname(String depname) {
        this.depname = depname == null ? null : depname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.DestName
     *
     * @return the value of Ord_OrderInfo.DestName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getDestname() {
        return destname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.DestName
     *
     * @param destname the value for Ord_OrderInfo.DestName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setDestname(String destname) {
        this.destname = destname == null ? null : destname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.DestID
     *
     * @return the value of Ord_OrderInfo.DestID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getDestid() {
        return destid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.DestID
     *
     * @param destid the value for Ord_OrderInfo.DestID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setDestid(String destid) {
        this.destid = destid == null ? null : destid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.OrderNo
     *
     * @return the value of Ord_OrderInfo.OrderNo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.OrderNo
     *
     * @param orderno the value for Ord_OrderInfo.OrderNo
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.CustomerUnitID
     *
     * @return the value of Ord_OrderInfo.CustomerUnitID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getCustomerunitid() {
        return customerunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.CustomerUnitID
     *
     * @param customerunitid the value for Ord_OrderInfo.CustomerUnitID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setCustomerunitid(String customerunitid) {
        this.customerunitid = customerunitid == null ? null : customerunitid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.CustomerName
     *
     * @return the value of Ord_OrderInfo.CustomerName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.CustomerName
     *
     * @param customername the value for Ord_OrderInfo.CustomerName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.OrderSourceID
     *
     * @return the value of Ord_OrderInfo.OrderSourceID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getOrdersourceid() {
        return ordersourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.OrderSourceID
     *
     * @param ordersourceid the value for Ord_OrderInfo.OrderSourceID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrdersourceid(String ordersourceid) {
        this.ordersourceid = ordersourceid == null ? null : ordersourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.OrderSource
     *
     * @return the value of Ord_OrderInfo.OrderSource
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getOrdersource() {
        return ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.OrderSource
     *
     * @param ordersource the value for Ord_OrderInfo.OrderSource
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrdersource(String ordersource) {
        this.ordersource = ordersource == null ? null : ordersource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.Contact
     *
     * @return the value of Ord_OrderInfo.Contact
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.Contact
     *
     * @param contact the value for Ord_OrderInfo.Contact
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.Mobile
     *
     * @return the value of Ord_OrderInfo.Mobile
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.Mobile
     *
     * @param mobile the value for Ord_OrderInfo.Mobile
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.HasAirTicket
     *
     * @return the value of Ord_OrderInfo.HasAirTicket
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getHasairticket() {
        return hasairticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.HasAirTicket
     *
     * @param hasairticket the value for Ord_OrderInfo.HasAirTicket
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setHasairticket(Integer hasairticket) {
        this.hasairticket = hasairticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.AdjustAmt
     *
     * @return the value of Ord_OrderInfo.AdjustAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public BigDecimal getAdjustamt() {
        return adjustamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.AdjustAmt
     *
     * @param adjustamt the value for Ord_OrderInfo.AdjustAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setAdjustamt(BigDecimal adjustamt) {
        this.adjustamt = adjustamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.ReceivableAmt
     *
     * @return the value of Ord_OrderInfo.ReceivableAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public BigDecimal getReceivableamt() {
        return receivableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.ReceivableAmt
     *
     * @param receivableamt the value for Ord_OrderInfo.ReceivableAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setReceivableamt(BigDecimal receivableamt) {
        this.receivableamt = receivableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.PayableAmt
     *
     * @return the value of Ord_OrderInfo.PayableAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public BigDecimal getPayableamt() {
        return payableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.PayableAmt
     *
     * @param payableamt the value for Ord_OrderInfo.PayableAmt
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setPayableamt(BigDecimal payableamt) {
        this.payableamt = payableamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.AdultNum
     *
     * @return the value of Ord_OrderInfo.AdultNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getAdultnum() {
        return adultnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.AdultNum
     *
     * @param adultnum the value for Ord_OrderInfo.AdultNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setAdultnum(Integer adultnum) {
        this.adultnum = adultnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.ChildNum
     *
     * @return the value of Ord_OrderInfo.ChildNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getChildnum() {
        return childnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.ChildNum
     *
     * @param childnum the value for Ord_OrderInfo.ChildNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setChildnum(Integer childnum) {
        this.childnum = childnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.GuideNum
     *
     * @return the value of Ord_OrderInfo.GuideNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getGuidenum() {
        return guidenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.GuideNum
     *
     * @param guidenum the value for Ord_OrderInfo.GuideNum
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setGuidenum(Integer guidenum) {
        this.guidenum = guidenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.Comment
     *
     * @return the value of Ord_OrderInfo.Comment
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.Comment
     *
     * @param comment the value for Ord_OrderInfo.Comment
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.CreatedDate
     *
     * @return the value of Ord_OrderInfo.CreatedDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.CreatedDate
     *
     * @param createddate the value for Ord_OrderInfo.CreatedDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.CreatedBy
     *
     * @return the value of Ord_OrderInfo.CreatedBy
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.CreatedBy
     *
     * @param createdby the value for Ord_OrderInfo.CreatedBy
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.CreatedByID
     *
     * @return the value of Ord_OrderInfo.CreatedByID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getCreatedbyid() {
        return createdbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.CreatedByID
     *
     * @param createdbyid the value for Ord_OrderInfo.CreatedByID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setCreatedbyid(String createdbyid) {
        this.createdbyid = createdbyid == null ? null : createdbyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.DeptID
     *
     * @return the value of Ord_OrderInfo.DeptID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.DeptID
     *
     * @param deptid the value for Ord_OrderInfo.DeptID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.RevisedDate
     *
     * @return the value of Ord_OrderInfo.RevisedDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Date getReviseddate() {
        return reviseddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.RevisedDate
     *
     * @param reviseddate the value for Ord_OrderInfo.RevisedDate
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setReviseddate(Date reviseddate) {
        this.reviseddate = reviseddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.RevisedBy
     *
     * @return the value of Ord_OrderInfo.RevisedBy
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getRevisedby() {
        return revisedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.RevisedBy
     *
     * @param revisedby the value for Ord_OrderInfo.RevisedBy
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setRevisedby(String revisedby) {
        this.revisedby = revisedby == null ? null : revisedby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.OrgID
     *
     * @return the value of Ord_OrderInfo.OrgID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.OrgID
     *
     * @param orgid the value for Ord_OrderInfo.OrgID
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.OrgName
     *
     * @return the value of Ord_OrderInfo.OrgName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getOrgname() {
        return orgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.OrgName
     *
     * @param orgname the value for Ord_OrderInfo.OrgName
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setOrgname(String orgname) {
        this.orgname = orgname == null ? null : orgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.DataStatus
     *
     * @return the value of Ord_OrderInfo.DataStatus
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.DataStatus
     *
     * @param datastatus the value for Ord_OrderInfo.DataStatus
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setDatastatus(Integer datastatus) {
        this.datastatus = datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.SignStatus
     *
     * @return the value of Ord_OrderInfo.SignStatus
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public Integer getSignstatus() {
        return signstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.SignStatus
     *
     * @param signstatus the value for Ord_OrderInfo.SignStatus
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setSignstatus(Integer signstatus) {
        this.signstatus = signstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ord_OrderInfo.TourGuide
     *
     * @return the value of Ord_OrderInfo.TourGuide
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public String getTourguide() {
        return tourguide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ord_OrderInfo.TourGuide
     *
     * @param tourguide the value for Ord_OrderInfo.TourGuide
     *
     * @mbggenerated Mon May 14 15:16:00 CST 2018
     */
    public void setTourguide(String tourguide) {
        this.tourguide = tourguide == null ? null : tourguide.trim();
    }
}