package com.zhou.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public ProProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProtypeidIsNull() {
            addCriterion("ProTypeID is null");
            return (Criteria) this;
        }

        public Criteria andProtypeidIsNotNull() {
            addCriterion("ProTypeID is not null");
            return (Criteria) this;
        }

        public Criteria andProtypeidEqualTo(String value) {
            addCriterion("ProTypeID =", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidNotEqualTo(String value) {
            addCriterion("ProTypeID <>", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidGreaterThan(String value) {
            addCriterion("ProTypeID >", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidGreaterThanOrEqualTo(String value) {
            addCriterion("ProTypeID >=", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidLessThan(String value) {
            addCriterion("ProTypeID <", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidLessThanOrEqualTo(String value) {
            addCriterion("ProTypeID <=", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidLike(String value) {
            addCriterion("ProTypeID like", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidNotLike(String value) {
            addCriterion("ProTypeID not like", value, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidIn(List<String> values) {
            addCriterion("ProTypeID in", values, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidNotIn(List<String> values) {
            addCriterion("ProTypeID not in", values, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidBetween(String value1, String value2) {
            addCriterion("ProTypeID between", value1, value2, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeidNotBetween(String value1, String value2) {
            addCriterion("ProTypeID not between", value1, value2, "protypeid");
            return (Criteria) this;
        }

        public Criteria andProtypeIsNull() {
            addCriterion("ProType is null");
            return (Criteria) this;
        }

        public Criteria andProtypeIsNotNull() {
            addCriterion("ProType is not null");
            return (Criteria) this;
        }

        public Criteria andProtypeEqualTo(String value) {
            addCriterion("ProType =", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeNotEqualTo(String value) {
            addCriterion("ProType <>", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeGreaterThan(String value) {
            addCriterion("ProType >", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeGreaterThanOrEqualTo(String value) {
            addCriterion("ProType >=", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeLessThan(String value) {
            addCriterion("ProType <", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeLessThanOrEqualTo(String value) {
            addCriterion("ProType <=", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeLike(String value) {
            addCriterion("ProType like", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeNotLike(String value) {
            addCriterion("ProType not like", value, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeIn(List<String> values) {
            addCriterion("ProType in", values, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeNotIn(List<String> values) {
            addCriterion("ProType not in", values, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeBetween(String value1, String value2) {
            addCriterion("ProType between", value1, value2, "protype");
            return (Criteria) this;
        }

        public Criteria andProtypeNotBetween(String value1, String value2) {
            addCriterion("ProType not between", value1, value2, "protype");
            return (Criteria) this;
        }

        public Criteria andProcategoryidIsNull() {
            addCriterion("ProCategoryID is null");
            return (Criteria) this;
        }

        public Criteria andProcategoryidIsNotNull() {
            addCriterion("ProCategoryID is not null");
            return (Criteria) this;
        }

        public Criteria andProcategoryidEqualTo(String value) {
            addCriterion("ProCategoryID =", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidNotEqualTo(String value) {
            addCriterion("ProCategoryID <>", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidGreaterThan(String value) {
            addCriterion("ProCategoryID >", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidGreaterThanOrEqualTo(String value) {
            addCriterion("ProCategoryID >=", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidLessThan(String value) {
            addCriterion("ProCategoryID <", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidLessThanOrEqualTo(String value) {
            addCriterion("ProCategoryID <=", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidLike(String value) {
            addCriterion("ProCategoryID like", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidNotLike(String value) {
            addCriterion("ProCategoryID not like", value, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidIn(List<String> values) {
            addCriterion("ProCategoryID in", values, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidNotIn(List<String> values) {
            addCriterion("ProCategoryID not in", values, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidBetween(String value1, String value2) {
            addCriterion("ProCategoryID between", value1, value2, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryidNotBetween(String value1, String value2) {
            addCriterion("ProCategoryID not between", value1, value2, "procategoryid");
            return (Criteria) this;
        }

        public Criteria andProcategoryIsNull() {
            addCriterion("ProCategory is null");
            return (Criteria) this;
        }

        public Criteria andProcategoryIsNotNull() {
            addCriterion("ProCategory is not null");
            return (Criteria) this;
        }

        public Criteria andProcategoryEqualTo(String value) {
            addCriterion("ProCategory =", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryNotEqualTo(String value) {
            addCriterion("ProCategory <>", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryGreaterThan(String value) {
            addCriterion("ProCategory >", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryGreaterThanOrEqualTo(String value) {
            addCriterion("ProCategory >=", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryLessThan(String value) {
            addCriterion("ProCategory <", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryLessThanOrEqualTo(String value) {
            addCriterion("ProCategory <=", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryLike(String value) {
            addCriterion("ProCategory like", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryNotLike(String value) {
            addCriterion("ProCategory not like", value, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryIn(List<String> values) {
            addCriterion("ProCategory in", values, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryNotIn(List<String> values) {
            addCriterion("ProCategory not in", values, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryBetween(String value1, String value2) {
            addCriterion("ProCategory between", value1, value2, "procategory");
            return (Criteria) this;
        }

        public Criteria andProcategoryNotBetween(String value1, String value2) {
            addCriterion("ProCategory not between", value1, value2, "procategory");
            return (Criteria) this;
        }

        public Criteria andPronameIsNull() {
            addCriterion("ProName is null");
            return (Criteria) this;
        }

        public Criteria andPronameIsNotNull() {
            addCriterion("ProName is not null");
            return (Criteria) this;
        }

        public Criteria andPronameEqualTo(String value) {
            addCriterion("ProName =", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotEqualTo(String value) {
            addCriterion("ProName <>", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThan(String value) {
            addCriterion("ProName >", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThanOrEqualTo(String value) {
            addCriterion("ProName >=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThan(String value) {
            addCriterion("ProName <", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThanOrEqualTo(String value) {
            addCriterion("ProName <=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLike(String value) {
            addCriterion("ProName like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotLike(String value) {
            addCriterion("ProName not like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameIn(List<String> values) {
            addCriterion("ProName in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotIn(List<String> values) {
            addCriterion("ProName not in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameBetween(String value1, String value2) {
            addCriterion("ProName between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotBetween(String value1, String value2) {
            addCriterion("ProName not between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andAliasenameIsNull() {
            addCriterion("AliaseName is null");
            return (Criteria) this;
        }

        public Criteria andAliasenameIsNotNull() {
            addCriterion("AliaseName is not null");
            return (Criteria) this;
        }

        public Criteria andAliasenameEqualTo(String value) {
            addCriterion("AliaseName =", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameNotEqualTo(String value) {
            addCriterion("AliaseName <>", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameGreaterThan(String value) {
            addCriterion("AliaseName >", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameGreaterThanOrEqualTo(String value) {
            addCriterion("AliaseName >=", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameLessThan(String value) {
            addCriterion("AliaseName <", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameLessThanOrEqualTo(String value) {
            addCriterion("AliaseName <=", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameLike(String value) {
            addCriterion("AliaseName like", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameNotLike(String value) {
            addCriterion("AliaseName not like", value, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameIn(List<String> values) {
            addCriterion("AliaseName in", values, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameNotIn(List<String> values) {
            addCriterion("AliaseName not in", values, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameBetween(String value1, String value2) {
            addCriterion("AliaseName between", value1, value2, "aliasename");
            return (Criteria) this;
        }

        public Criteria andAliasenameNotBetween(String value1, String value2) {
            addCriterion("AliaseName not between", value1, value2, "aliasename");
            return (Criteria) this;
        }

        public Criteria andPronoIsNull() {
            addCriterion("ProNo is null");
            return (Criteria) this;
        }

        public Criteria andPronoIsNotNull() {
            addCriterion("ProNo is not null");
            return (Criteria) this;
        }

        public Criteria andPronoEqualTo(String value) {
            addCriterion("ProNo =", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoNotEqualTo(String value) {
            addCriterion("ProNo <>", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoGreaterThan(String value) {
            addCriterion("ProNo >", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoGreaterThanOrEqualTo(String value) {
            addCriterion("ProNo >=", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoLessThan(String value) {
            addCriterion("ProNo <", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoLessThanOrEqualTo(String value) {
            addCriterion("ProNo <=", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoLike(String value) {
            addCriterion("ProNo like", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoNotLike(String value) {
            addCriterion("ProNo not like", value, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoIn(List<String> values) {
            addCriterion("ProNo in", values, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoNotIn(List<String> values) {
            addCriterion("ProNo not in", values, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoBetween(String value1, String value2) {
            addCriterion("ProNo between", value1, value2, "prono");
            return (Criteria) this;
        }

        public Criteria andPronoNotBetween(String value1, String value2) {
            addCriterion("ProNo not between", value1, value2, "prono");
            return (Criteria) this;
        }

        public Criteria andTourdaysIsNull() {
            addCriterion("TourDays is null");
            return (Criteria) this;
        }

        public Criteria andTourdaysIsNotNull() {
            addCriterion("TourDays is not null");
            return (Criteria) this;
        }

        public Criteria andTourdaysEqualTo(Integer value) {
            addCriterion("TourDays =", value, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysNotEqualTo(Integer value) {
            addCriterion("TourDays <>", value, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysGreaterThan(Integer value) {
            addCriterion("TourDays >", value, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("TourDays >=", value, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysLessThan(Integer value) {
            addCriterion("TourDays <", value, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysLessThanOrEqualTo(Integer value) {
            addCriterion("TourDays <=", value, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysIn(List<Integer> values) {
            addCriterion("TourDays in", values, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysNotIn(List<Integer> values) {
            addCriterion("TourDays not in", values, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysBetween(Integer value1, Integer value2) {
            addCriterion("TourDays between", value1, value2, "tourdays");
            return (Criteria) this;
        }

        public Criteria andTourdaysNotBetween(Integer value1, Integer value2) {
            addCriterion("TourDays not between", value1, value2, "tourdays");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("StartDate is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("StartDate is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterion("StartDate =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterion("StartDate <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterion("StartDate >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("StartDate >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterion("StartDate <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterion("StartDate <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterion("StartDate in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterion("StartDate not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterion("StartDate between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterion("StartDate not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andDuedateIsNull() {
            addCriterion("DueDate is null");
            return (Criteria) this;
        }

        public Criteria andDuedateIsNotNull() {
            addCriterion("DueDate is not null");
            return (Criteria) this;
        }

        public Criteria andDuedateEqualTo(Date value) {
            addCriterion("DueDate =", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotEqualTo(Date value) {
            addCriterion("DueDate <>", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateGreaterThan(Date value) {
            addCriterion("DueDate >", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateGreaterThanOrEqualTo(Date value) {
            addCriterion("DueDate >=", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateLessThan(Date value) {
            addCriterion("DueDate <", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateLessThanOrEqualTo(Date value) {
            addCriterion("DueDate <=", value, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateIn(List<Date> values) {
            addCriterion("DueDate in", values, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotIn(List<Date> values) {
            addCriterion("DueDate not in", values, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateBetween(Date value1, Date value2) {
            addCriterion("DueDate between", value1, value2, "duedate");
            return (Criteria) this;
        }

        public Criteria andDuedateNotBetween(Date value1, Date value2) {
            addCriterion("DueDate not between", value1, value2, "duedate");
            return (Criteria) this;
        }

        public Criteria andDepartureIsNull() {
            addCriterion("Departure is null");
            return (Criteria) this;
        }

        public Criteria andDepartureIsNotNull() {
            addCriterion("Departure is not null");
            return (Criteria) this;
        }

        public Criteria andDepartureEqualTo(String value) {
            addCriterion("Departure =", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureNotEqualTo(String value) {
            addCriterion("Departure <>", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureGreaterThan(String value) {
            addCriterion("Departure >", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureGreaterThanOrEqualTo(String value) {
            addCriterion("Departure >=", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureLessThan(String value) {
            addCriterion("Departure <", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureLessThanOrEqualTo(String value) {
            addCriterion("Departure <=", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureLike(String value) {
            addCriterion("Departure like", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureNotLike(String value) {
            addCriterion("Departure not like", value, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureIn(List<String> values) {
            addCriterion("Departure in", values, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureNotIn(List<String> values) {
            addCriterion("Departure not in", values, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureBetween(String value1, String value2) {
            addCriterion("Departure between", value1, value2, "departure");
            return (Criteria) this;
        }

        public Criteria andDepartureNotBetween(String value1, String value2) {
            addCriterion("Departure not between", value1, value2, "departure");
            return (Criteria) this;
        }

        public Criteria andDestinationIsNull() {
            addCriterion("Destination is null");
            return (Criteria) this;
        }

        public Criteria andDestinationIsNotNull() {
            addCriterion("Destination is not null");
            return (Criteria) this;
        }

        public Criteria andDestinationEqualTo(String value) {
            addCriterion("Destination =", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotEqualTo(String value) {
            addCriterion("Destination <>", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationGreaterThan(String value) {
            addCriterion("Destination >", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationGreaterThanOrEqualTo(String value) {
            addCriterion("Destination >=", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLessThan(String value) {
            addCriterion("Destination <", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLessThanOrEqualTo(String value) {
            addCriterion("Destination <=", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationLike(String value) {
            addCriterion("Destination like", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotLike(String value) {
            addCriterion("Destination not like", value, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationIn(List<String> values) {
            addCriterion("Destination in", values, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotIn(List<String> values) {
            addCriterion("Destination not in", values, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationBetween(String value1, String value2) {
            addCriterion("Destination between", value1, value2, "destination");
            return (Criteria) this;
        }

        public Criteria andDestinationNotBetween(String value1, String value2) {
            addCriterion("Destination not between", value1, value2, "destination");
            return (Criteria) this;
        }

        public Criteria andProtagIsNull() {
            addCriterion("ProTag is null");
            return (Criteria) this;
        }

        public Criteria andProtagIsNotNull() {
            addCriterion("ProTag is not null");
            return (Criteria) this;
        }

        public Criteria andProtagEqualTo(String value) {
            addCriterion("ProTag =", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagNotEqualTo(String value) {
            addCriterion("ProTag <>", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagGreaterThan(String value) {
            addCriterion("ProTag >", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagGreaterThanOrEqualTo(String value) {
            addCriterion("ProTag >=", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagLessThan(String value) {
            addCriterion("ProTag <", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagLessThanOrEqualTo(String value) {
            addCriterion("ProTag <=", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagLike(String value) {
            addCriterion("ProTag like", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagNotLike(String value) {
            addCriterion("ProTag not like", value, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagIn(List<String> values) {
            addCriterion("ProTag in", values, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagNotIn(List<String> values) {
            addCriterion("ProTag not in", values, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagBetween(String value1, String value2) {
            addCriterion("ProTag between", value1, value2, "protag");
            return (Criteria) this;
        }

        public Criteria andProtagNotBetween(String value1, String value2) {
            addCriterion("ProTag not between", value1, value2, "protag");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNull() {
            addCriterion("Feature is null");
            return (Criteria) this;
        }

        public Criteria andFeatureIsNotNull() {
            addCriterion("Feature is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureEqualTo(String value) {
            addCriterion("Feature =", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotEqualTo(String value) {
            addCriterion("Feature <>", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThan(String value) {
            addCriterion("Feature >", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureGreaterThanOrEqualTo(String value) {
            addCriterion("Feature >=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThan(String value) {
            addCriterion("Feature <", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLessThanOrEqualTo(String value) {
            addCriterion("Feature <=", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureLike(String value) {
            addCriterion("Feature like", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotLike(String value) {
            addCriterion("Feature not like", value, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureIn(List<String> values) {
            addCriterion("Feature in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotIn(List<String> values) {
            addCriterion("Feature not in", values, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureBetween(String value1, String value2) {
            addCriterion("Feature between", value1, value2, "feature");
            return (Criteria) this;
        }

        public Criteria andFeatureNotBetween(String value1, String value2) {
            addCriterion("Feature not between", value1, value2, "feature");
            return (Criteria) this;
        }

        public Criteria andFeeincludesIsNull() {
            addCriterion("FeeIncludes is null");
            return (Criteria) this;
        }

        public Criteria andFeeincludesIsNotNull() {
            addCriterion("FeeIncludes is not null");
            return (Criteria) this;
        }

        public Criteria andFeeincludesEqualTo(String value) {
            addCriterion("FeeIncludes =", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesNotEqualTo(String value) {
            addCriterion("FeeIncludes <>", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesGreaterThan(String value) {
            addCriterion("FeeIncludes >", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesGreaterThanOrEqualTo(String value) {
            addCriterion("FeeIncludes >=", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesLessThan(String value) {
            addCriterion("FeeIncludes <", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesLessThanOrEqualTo(String value) {
            addCriterion("FeeIncludes <=", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesLike(String value) {
            addCriterion("FeeIncludes like", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesNotLike(String value) {
            addCriterion("FeeIncludes not like", value, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesIn(List<String> values) {
            addCriterion("FeeIncludes in", values, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesNotIn(List<String> values) {
            addCriterion("FeeIncludes not in", values, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesBetween(String value1, String value2) {
            addCriterion("FeeIncludes between", value1, value2, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeeincludesNotBetween(String value1, String value2) {
            addCriterion("FeeIncludes not between", value1, value2, "feeincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesIsNull() {
            addCriterion("FeeNonIncludes is null");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesIsNotNull() {
            addCriterion("FeeNonIncludes is not null");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesEqualTo(String value) {
            addCriterion("FeeNonIncludes =", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesNotEqualTo(String value) {
            addCriterion("FeeNonIncludes <>", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesGreaterThan(String value) {
            addCriterion("FeeNonIncludes >", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesGreaterThanOrEqualTo(String value) {
            addCriterion("FeeNonIncludes >=", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesLessThan(String value) {
            addCriterion("FeeNonIncludes <", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesLessThanOrEqualTo(String value) {
            addCriterion("FeeNonIncludes <=", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesLike(String value) {
            addCriterion("FeeNonIncludes like", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesNotLike(String value) {
            addCriterion("FeeNonIncludes not like", value, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesIn(List<String> values) {
            addCriterion("FeeNonIncludes in", values, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesNotIn(List<String> values) {
            addCriterion("FeeNonIncludes not in", values, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesBetween(String value1, String value2) {
            addCriterion("FeeNonIncludes between", value1, value2, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andFeenonincludesNotBetween(String value1, String value2) {
            addCriterion("FeeNonIncludes not between", value1, value2, "feenonincludes");
            return (Criteria) this;
        }

        public Criteria andCoverimgIsNull() {
            addCriterion("CoverImg is null");
            return (Criteria) this;
        }

        public Criteria andCoverimgIsNotNull() {
            addCriterion("CoverImg is not null");
            return (Criteria) this;
        }

        public Criteria andCoverimgEqualTo(String value) {
            addCriterion("CoverImg =", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgNotEqualTo(String value) {
            addCriterion("CoverImg <>", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgGreaterThan(String value) {
            addCriterion("CoverImg >", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgGreaterThanOrEqualTo(String value) {
            addCriterion("CoverImg >=", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgLessThan(String value) {
            addCriterion("CoverImg <", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgLessThanOrEqualTo(String value) {
            addCriterion("CoverImg <=", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgLike(String value) {
            addCriterion("CoverImg like", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgNotLike(String value) {
            addCriterion("CoverImg not like", value, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgIn(List<String> values) {
            addCriterion("CoverImg in", values, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgNotIn(List<String> values) {
            addCriterion("CoverImg not in", values, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgBetween(String value1, String value2) {
            addCriterion("CoverImg between", value1, value2, "coverimg");
            return (Criteria) this;
        }

        public Criteria andCoverimgNotBetween(String value1, String value2) {
            addCriterion("CoverImg not between", value1, value2, "coverimg");
            return (Criteria) this;
        }

        public Criteria andIsackIsNull() {
            addCriterion("IsAck is null");
            return (Criteria) this;
        }

        public Criteria andIsackIsNotNull() {
            addCriterion("IsAck is not null");
            return (Criteria) this;
        }

        public Criteria andIsackEqualTo(Integer value) {
            addCriterion("IsAck =", value, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackNotEqualTo(Integer value) {
            addCriterion("IsAck <>", value, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackGreaterThan(Integer value) {
            addCriterion("IsAck >", value, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackGreaterThanOrEqualTo(Integer value) {
            addCriterion("IsAck >=", value, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackLessThan(Integer value) {
            addCriterion("IsAck <", value, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackLessThanOrEqualTo(Integer value) {
            addCriterion("IsAck <=", value, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackIn(List<Integer> values) {
            addCriterion("IsAck in", values, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackNotIn(List<Integer> values) {
            addCriterion("IsAck not in", values, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackBetween(Integer value1, Integer value2) {
            addCriterion("IsAck between", value1, value2, "isack");
            return (Criteria) this;
        }

        public Criteria andIsackNotBetween(Integer value1, Integer value2) {
            addCriterion("IsAck not between", value1, value2, "isack");
            return (Criteria) this;
        }

        public Criteria andDatastatusIsNull() {
            addCriterion("DataStatus is null");
            return (Criteria) this;
        }

        public Criteria andDatastatusIsNotNull() {
            addCriterion("DataStatus is not null");
            return (Criteria) this;
        }

        public Criteria andDatastatusEqualTo(Integer value) {
            addCriterion("DataStatus =", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusNotEqualTo(Integer value) {
            addCriterion("DataStatus <>", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusGreaterThan(Integer value) {
            addCriterion("DataStatus >", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("DataStatus >=", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusLessThan(Integer value) {
            addCriterion("DataStatus <", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusLessThanOrEqualTo(Integer value) {
            addCriterion("DataStatus <=", value, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusIn(List<Integer> values) {
            addCriterion("DataStatus in", values, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusNotIn(List<Integer> values) {
            addCriterion("DataStatus not in", values, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusBetween(Integer value1, Integer value2) {
            addCriterion("DataStatus between", value1, value2, "datastatus");
            return (Criteria) this;
        }

        public Criteria andDatastatusNotBetween(Integer value1, Integer value2) {
            addCriterion("DataStatus not between", value1, value2, "datastatus");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNull() {
            addCriterion("CreatedDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateddateIsNotNull() {
            addCriterion("CreatedDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateddateEqualTo(Date value) {
            addCriterion("CreatedDate =", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotEqualTo(Date value) {
            addCriterion("CreatedDate <>", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThan(Date value) {
            addCriterion("CreatedDate >", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
            addCriterion("CreatedDate >=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThan(Date value) {
            addCriterion("CreatedDate <", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateLessThanOrEqualTo(Date value) {
            addCriterion("CreatedDate <=", value, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateIn(List<Date> values) {
            addCriterion("CreatedDate in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotIn(List<Date> values) {
            addCriterion("CreatedDate not in", values, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateBetween(Date value1, Date value2) {
            addCriterion("CreatedDate between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreateddateNotBetween(Date value1, Date value2) {
            addCriterion("CreatedDate not between", value1, value2, "createddate");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNull() {
            addCriterion("CreatedBy is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIsNotNull() {
            addCriterion("CreatedBy is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyEqualTo(String value) {
            addCriterion("CreatedBy =", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotEqualTo(String value) {
            addCriterion("CreatedBy <>", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThan(String value) {
            addCriterion("CreatedBy >", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedBy >=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThan(String value) {
            addCriterion("CreatedBy <", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLessThanOrEqualTo(String value) {
            addCriterion("CreatedBy <=", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyLike(String value) {
            addCriterion("CreatedBy like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotLike(String value) {
            addCriterion("CreatedBy not like", value, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyIn(List<String> values) {
            addCriterion("CreatedBy in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotIn(List<String> values) {
            addCriterion("CreatedBy not in", values, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyBetween(String value1, String value2) {
            addCriterion("CreatedBy between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyNotBetween(String value1, String value2) {
            addCriterion("CreatedBy not between", value1, value2, "createdby");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidIsNull() {
            addCriterion("CreatedByID is null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidIsNotNull() {
            addCriterion("CreatedByID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidEqualTo(String value) {
            addCriterion("CreatedByID =", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotEqualTo(String value) {
            addCriterion("CreatedByID <>", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidGreaterThan(String value) {
            addCriterion("CreatedByID >", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidGreaterThanOrEqualTo(String value) {
            addCriterion("CreatedByID >=", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidLessThan(String value) {
            addCriterion("CreatedByID <", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidLessThanOrEqualTo(String value) {
            addCriterion("CreatedByID <=", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidLike(String value) {
            addCriterion("CreatedByID like", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotLike(String value) {
            addCriterion("CreatedByID not like", value, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidIn(List<String> values) {
            addCriterion("CreatedByID in", values, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotIn(List<String> values) {
            addCriterion("CreatedByID not in", values, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidBetween(String value1, String value2) {
            addCriterion("CreatedByID between", value1, value2, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andCreatedbyidNotBetween(String value1, String value2) {
            addCriterion("CreatedByID not between", value1, value2, "createdbyid");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNull() {
            addCriterion("DeptID is null");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNotNull() {
            addCriterion("DeptID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptidEqualTo(String value) {
            addCriterion("DeptID =", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotEqualTo(String value) {
            addCriterion("DeptID <>", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThan(String value) {
            addCriterion("DeptID >", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("DeptID >=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThan(String value) {
            addCriterion("DeptID <", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThanOrEqualTo(String value) {
            addCriterion("DeptID <=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLike(String value) {
            addCriterion("DeptID like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotLike(String value) {
            addCriterion("DeptID not like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidIn(List<String> values) {
            addCriterion("DeptID in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotIn(List<String> values) {
            addCriterion("DeptID not in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidBetween(String value1, String value2) {
            addCriterion("DeptID between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotBetween(String value1, String value2) {
            addCriterion("DeptID not between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNull() {
            addCriterion("OrgID is null");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNotNull() {
            addCriterion("OrgID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidEqualTo(String value) {
            addCriterion("OrgID =", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotEqualTo(String value) {
            addCriterion("OrgID <>", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThan(String value) {
            addCriterion("OrgID >", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThanOrEqualTo(String value) {
            addCriterion("OrgID >=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThan(String value) {
            addCriterion("OrgID <", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThanOrEqualTo(String value) {
            addCriterion("OrgID <=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLike(String value) {
            addCriterion("OrgID like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotLike(String value) {
            addCriterion("OrgID not like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidIn(List<String> values) {
            addCriterion("OrgID in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotIn(List<String> values) {
            addCriterion("OrgID not in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidBetween(String value1, String value2) {
            addCriterion("OrgID between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotBetween(String value1, String value2) {
            addCriterion("OrgID not between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andReviseddateIsNull() {
            addCriterion("RevisedDate is null");
            return (Criteria) this;
        }

        public Criteria andReviseddateIsNotNull() {
            addCriterion("RevisedDate is not null");
            return (Criteria) this;
        }

        public Criteria andReviseddateEqualTo(Date value) {
            addCriterion("RevisedDate =", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateNotEqualTo(Date value) {
            addCriterion("RevisedDate <>", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateGreaterThan(Date value) {
            addCriterion("RevisedDate >", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateGreaterThanOrEqualTo(Date value) {
            addCriterion("RevisedDate >=", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateLessThan(Date value) {
            addCriterion("RevisedDate <", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateLessThanOrEqualTo(Date value) {
            addCriterion("RevisedDate <=", value, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateIn(List<Date> values) {
            addCriterion("RevisedDate in", values, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateNotIn(List<Date> values) {
            addCriterion("RevisedDate not in", values, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateBetween(Date value1, Date value2) {
            addCriterion("RevisedDate between", value1, value2, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andReviseddateNotBetween(Date value1, Date value2) {
            addCriterion("RevisedDate not between", value1, value2, "reviseddate");
            return (Criteria) this;
        }

        public Criteria andRevisedbyIsNull() {
            addCriterion("RevisedBy is null");
            return (Criteria) this;
        }

        public Criteria andRevisedbyIsNotNull() {
            addCriterion("RevisedBy is not null");
            return (Criteria) this;
        }

        public Criteria andRevisedbyEqualTo(String value) {
            addCriterion("RevisedBy =", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotEqualTo(String value) {
            addCriterion("RevisedBy <>", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyGreaterThan(String value) {
            addCriterion("RevisedBy >", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyGreaterThanOrEqualTo(String value) {
            addCriterion("RevisedBy >=", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyLessThan(String value) {
            addCriterion("RevisedBy <", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyLessThanOrEqualTo(String value) {
            addCriterion("RevisedBy <=", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyLike(String value) {
            addCriterion("RevisedBy like", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotLike(String value) {
            addCriterion("RevisedBy not like", value, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyIn(List<String> values) {
            addCriterion("RevisedBy in", values, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotIn(List<String> values) {
            addCriterion("RevisedBy not in", values, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyBetween(String value1, String value2) {
            addCriterion("RevisedBy between", value1, value2, "revisedby");
            return (Criteria) this;
        }

        public Criteria andRevisedbyNotBetween(String value1, String value2) {
            addCriterion("RevisedBy not between", value1, value2, "revisedby");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Pro_Product
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 19 14:27:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Pro_Product
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}