package com.zhou.pojo;

import java.util.Date;

public class ProProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ProTypeID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String protypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ProType
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String protype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ProCategoryID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String procategoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ProCategory
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String procategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ProName
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String proname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.AliaseName
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String aliasename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ProNo
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String prono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.TourDays
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private Integer tourdays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.StartDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.DueDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private Date duedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Departure
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String departure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Destination
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.ProTag
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String protag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Feature
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.FeeIncludes
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String feeincludes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.FeeNonIncludes
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String feenonincludes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.CoverImg
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String coverimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.IsAck
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private Integer isack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.DataStatus
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private Integer datastatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.CreatedDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private Date createddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.CreatedBy
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.CreatedByID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String createdbyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.DeptID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.OrgID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.RevisedDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private Date reviseddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.RevisedBy
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String revisedby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ID
     *
     * @return the value of Pro_Product.ID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ID
     *
     * @param id the value for Pro_Product.ID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ProTypeID
     *
     * @return the value of Pro_Product.ProTypeID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getProtypeid() {
        return protypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ProTypeID
     *
     * @param protypeid the value for Pro_Product.ProTypeID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setProtypeid(String protypeid) {
        this.protypeid = protypeid == null ? null : protypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ProType
     *
     * @return the value of Pro_Product.ProType
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getProtype() {
        return protype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ProType
     *
     * @param protype the value for Pro_Product.ProType
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setProtype(String protype) {
        this.protype = protype == null ? null : protype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ProCategoryID
     *
     * @return the value of Pro_Product.ProCategoryID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getProcategoryid() {
        return procategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ProCategoryID
     *
     * @param procategoryid the value for Pro_Product.ProCategoryID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setProcategoryid(String procategoryid) {
        this.procategoryid = procategoryid == null ? null : procategoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ProCategory
     *
     * @return the value of Pro_Product.ProCategory
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getProcategory() {
        return procategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ProCategory
     *
     * @param procategory the value for Pro_Product.ProCategory
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setProcategory(String procategory) {
        this.procategory = procategory == null ? null : procategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ProName
     *
     * @return the value of Pro_Product.ProName
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ProName
     *
     * @param proname the value for Pro_Product.ProName
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.AliaseName
     *
     * @return the value of Pro_Product.AliaseName
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getAliasename() {
        return aliasename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.AliaseName
     *
     * @param aliasename the value for Pro_Product.AliaseName
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setAliasename(String aliasename) {
        this.aliasename = aliasename == null ? null : aliasename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ProNo
     *
     * @return the value of Pro_Product.ProNo
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getProno() {
        return prono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ProNo
     *
     * @param prono the value for Pro_Product.ProNo
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setProno(String prono) {
        this.prono = prono == null ? null : prono.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.TourDays
     *
     * @return the value of Pro_Product.TourDays
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Integer getTourdays() {
        return tourdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.TourDays
     *
     * @param tourdays the value for Pro_Product.TourDays
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setTourdays(Integer tourdays) {
        this.tourdays = tourdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.StartDate
     *
     * @return the value of Pro_Product.StartDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.StartDate
     *
     * @param startdate the value for Pro_Product.StartDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.DueDate
     *
     * @return the value of Pro_Product.DueDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Date getDuedate() {
        return duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.DueDate
     *
     * @param duedate the value for Pro_Product.DueDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Departure
     *
     * @return the value of Pro_Product.Departure
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Departure
     *
     * @param departure the value for Pro_Product.Departure
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setDeparture(String departure) {
        this.departure = departure == null ? null : departure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Destination
     *
     * @return the value of Pro_Product.Destination
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Destination
     *
     * @param destination the value for Pro_Product.Destination
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.ProTag
     *
     * @return the value of Pro_Product.ProTag
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getProtag() {
        return protag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.ProTag
     *
     * @param protag the value for Pro_Product.ProTag
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setProtag(String protag) {
        this.protag = protag == null ? null : protag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Feature
     *
     * @return the value of Pro_Product.Feature
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Feature
     *
     * @param feature the value for Pro_Product.Feature
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.FeeIncludes
     *
     * @return the value of Pro_Product.FeeIncludes
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getFeeincludes() {
        return feeincludes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.FeeIncludes
     *
     * @param feeincludes the value for Pro_Product.FeeIncludes
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setFeeincludes(String feeincludes) {
        this.feeincludes = feeincludes == null ? null : feeincludes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.FeeNonIncludes
     *
     * @return the value of Pro_Product.FeeNonIncludes
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getFeenonincludes() {
        return feenonincludes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.FeeNonIncludes
     *
     * @param feenonincludes the value for Pro_Product.FeeNonIncludes
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setFeenonincludes(String feenonincludes) {
        this.feenonincludes = feenonincludes == null ? null : feenonincludes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.CoverImg
     *
     * @return the value of Pro_Product.CoverImg
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getCoverimg() {
        return coverimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.CoverImg
     *
     * @param coverimg the value for Pro_Product.CoverImg
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setCoverimg(String coverimg) {
        this.coverimg = coverimg == null ? null : coverimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.IsAck
     *
     * @return the value of Pro_Product.IsAck
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Integer getIsack() {
        return isack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.IsAck
     *
     * @param isack the value for Pro_Product.IsAck
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setIsack(Integer isack) {
        this.isack = isack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.DataStatus
     *
     * @return the value of Pro_Product.DataStatus
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Integer getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.DataStatus
     *
     * @param datastatus the value for Pro_Product.DataStatus
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setDatastatus(Integer datastatus) {
        this.datastatus = datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.CreatedDate
     *
     * @return the value of Pro_Product.CreatedDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.CreatedDate
     *
     * @param createddate the value for Pro_Product.CreatedDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.CreatedBy
     *
     * @return the value of Pro_Product.CreatedBy
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.CreatedBy
     *
     * @param createdby the value for Pro_Product.CreatedBy
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.CreatedByID
     *
     * @return the value of Pro_Product.CreatedByID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getCreatedbyid() {
        return createdbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.CreatedByID
     *
     * @param createdbyid the value for Pro_Product.CreatedByID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setCreatedbyid(String createdbyid) {
        this.createdbyid = createdbyid == null ? null : createdbyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.DeptID
     *
     * @return the value of Pro_Product.DeptID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.DeptID
     *
     * @param deptid the value for Pro_Product.DeptID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid == null ? null : deptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.OrgID
     *
     * @return the value of Pro_Product.OrgID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.OrgID
     *
     * @param orgid the value for Pro_Product.OrgID
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.RevisedDate
     *
     * @return the value of Pro_Product.RevisedDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public Date getReviseddate() {
        return reviseddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.RevisedDate
     *
     * @param reviseddate the value for Pro_Product.RevisedDate
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setReviseddate(Date reviseddate) {
        this.reviseddate = reviseddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.RevisedBy
     *
     * @return the value of Pro_Product.RevisedBy
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getRevisedby() {
        return revisedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.RevisedBy
     *
     * @param revisedby the value for Pro_Product.RevisedBy
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setRevisedby(String revisedby) {
        this.revisedby = revisedby == null ? null : revisedby.trim();
    }
}