package com.zhou.pojo;

public class ProProductWithBLOBs extends ProProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Summary
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Attention
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String attention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Shopping
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String shopping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Tips
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String tips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.Insurance
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String insurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Pro_Product.BacToRule
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    private String bactorule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Summary
     *
     * @return the value of Pro_Product.Summary
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Summary
     *
     * @param summary the value for Pro_Product.Summary
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Attention
     *
     * @return the value of Pro_Product.Attention
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Attention
     *
     * @param attention the value for Pro_Product.Attention
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setAttention(String attention) {
        this.attention = attention == null ? null : attention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Shopping
     *
     * @return the value of Pro_Product.Shopping
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getShopping() {
        return shopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Shopping
     *
     * @param shopping the value for Pro_Product.Shopping
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setShopping(String shopping) {
        this.shopping = shopping == null ? null : shopping.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Tips
     *
     * @return the value of Pro_Product.Tips
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Tips
     *
     * @param tips the value for Pro_Product.Tips
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setTips(String tips) {
        this.tips = tips == null ? null : tips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.Insurance
     *
     * @return the value of Pro_Product.Insurance
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.Insurance
     *
     * @param insurance the value for Pro_Product.Insurance
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setInsurance(String insurance) {
        this.insurance = insurance == null ? null : insurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Pro_Product.BacToRule
     *
     * @return the value of Pro_Product.BacToRule
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public String getBactorule() {
        return bactorule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Pro_Product.BacToRule
     *
     * @param bactorule the value for Pro_Product.BacToRule
     *
     * @mbggenerated Mon Mar 19 14:27:45 CST 2018
     */
    public void setBactorule(String bactorule) {
        this.bactorule = bactorule == null ? null : bactorule.trim();
    }
}